[build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"

[deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT tandem.asgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
