[build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input"

[deploy]
startCommand = "python manage.py migrate && daphne -b 0.0.0.0 -p $PORT tandem.asgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
